/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    EventDto,
    EventDtoFromJSON,
    EventDtoToJSON,
    EventsQueryDto,
    EventsQueryDtoFromJSON,
    EventsQueryDtoToJSON,
} from '../models';

export interface ApiGamesGameIdEventsQueryPostRequest {
    gameId: number;
    eventsQueryDto?: EventsQueryDto;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     */
    async apiGamesGameIdEventsQueryPostRaw(requestParameters: ApiGamesGameIdEventsQueryPostRequest): Promise<runtime.ApiResponse<Array<EventDto>>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling apiGamesGameIdEventsQueryPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/api/games/{gameId}/events/query`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventsQueryDtoToJSON(requestParameters.eventsQueryDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventDtoFromJSON));
    }

    /**
     */
    async apiGamesGameIdEventsQueryPost(requestParameters: ApiGamesGameIdEventsQueryPostRequest): Promise<Array<EventDto>> {
        const response = await this.apiGamesGameIdEventsQueryPostRaw(requestParameters);
        return await response.value();
    }

}
