export default interface Theme {

    cellColorCenter? : string,
    cellColorEven? : string,
    cellColorOdd? : string,

    cellHighlightSelectedColor? : string,
    cellHighlightSelectedIntensity? : number,
    cellHighlightSelectionOptionColor? : string,
    cellHighlightSelectionOptionIntensity? : number,

    centerCellName? : string,

    effectMessageGameStatusChangedStarted? : string,
    effectMessageGameStatusChangedFinished? : string,
    effectMessageNeutralPlayerAdded? : string,
    effectMessagePieceAbandoned? : string,
    effectMessagePieceDropped? : string,
    effectMessagePieceEnlisted? : string,
    effectMessagePieceKilled? : string,
    effectMessagePieceMoved? : string,
    effectMessagePieceVacated? : string,
    effectMessagePlayerAdded? : string,
    effectMessagePlayerOutOfMoves? : string,
    effectMessagePlayerRemoved? : string,
    effectMessagePlayerStatusChangedAlive? : string,
    effectMessagePlayerStatusChangedAcceptsDraw? : string,
    effectMessagePlayerStatusChangedConceded? : string,
    effectMessagePlayerStatusChangedWillConcede? : string,
    effectMessagePlayerStatusChangedEliminated? : string,
    effectMessagePlayerStatusChangedVictorious? : string,
    effectMessageTurnCycleAdvanced? : string,
    effectMessageTurnCyclePlayerFellFromPower? : string,
    effectMessageTurnCyclePlayerRemoved? : string,
    effectMessageTurnCyclePlayerRoseToPower? : string,

    eventMessageGameStarted? : string,
    eventMessageTurnCommitted? : string,
    eventMessagePlayerStatusChanged? : string,

    pieceImageAssassin? : string,
    pieceImageChief? : string,
    pieceImageCorpse? : string,
    pieceImageDiplomat? : string,
    pieceImageGravedigger? : string,
    pieceImageReporter? : string,
    pieceImageThug? : string,

    pieceNameAssassin? : string,
    pieceNameChief? : string,
    pieceNameCorpse? : string,
    pieceNameDiplomat? : string,
    pieceNameGravedigger? : string,
    pieceNameReporter? : string,
    pieceNameThug? : string,

    playerColor0? : string,
    playerColor1? : string,
    playerColor2? : string,
    playerColor3? : string,
    playerColor4? : string,
    playerColor5? : string,
    playerColor6? : string,
    playerColor7? : string,

    selectionDescriptionDrop? : string,
    selectionDescriptionMove? : string,
    selectionDescriptionMoveAndTarget? : string,
    selectionDescriptionSubject? : string,
    selectionDescriptionTarget? : string,
    selectionDescriptionVacate? : string,

    selectionPromptDrop? : string,
    selectionPromptMove? : string,
    selectionPromptNull? : string,
    selectionPromptSubject? : string,
    selectionPromptTarget? : string,
    selectionPromptVacate? : string,

    turnPromptCommit? : string,
    turnPromptDeadEnd? : string
}
