export default interface Theme {

    cellColorCenter : string,
    cellColorEven : string,
    cellColorOdd : string,

    cellHighlightSelectedColor : string,
    cellHighlightSelectedIntensity : number,
    cellHighlightSelectionOptionColor : string,
    cellHighlightSelectionOptionIntensity : number,

    centerCellName : string,

    effectMessageGameStatusChanged : string,
    effectMessageNeutralPlayerAdded : string,
    effectMessagePieceAbandoned : string,
    effectMessagePieceDropped : string,
    effectMessagePieceEnlisted : string,
    effectMessagePieceKilled : string,
    effectMessagePieceMoved : string,
    effectMessagePieceVacated : string,
    effectMessagePlayerAdded : string,
    effectMessagePlayerEliminated : string,
    effectMessagePlayerOutOfMoves : string,
    effectMessagePlayerRemoved : string,
    effectMessageTurnCycleChanged : string,

    eventMessageGameStarted : string,
    eventMessagePlayerEjected : string,
    eventMessagePlayerQuit : string,
    eventMessageTurnCommitted : string,

    pieceImageAssassin : string,
    pieceImageChief : string,
    pieceImageCorpse : string,
    pieceImageDiplomat : string,
    pieceImageGravedigger : string,
    pieceImageReporter : string,
    pieceImageThug: string,

    pieceNameAssassin : string,
    pieceNameChief : string,
    pieceNameCorpse : string,
    pieceNameDiplomat : string,
    pieceNameGravedigger : string,
    pieceNameReporter : string,
    pieceNameThug : string,

    playerColor0 : string,
    playerColor1 : string,
    playerColor2 : string,
    playerColor3 : string,
    playerColor4 : string,
    playerColor5 : string,
    playerColor6 : string,
    playerColor7 : string,

    selectionDescriptionDrop : string,
    selectionDescriptionMove : string,
    selectionDescriptionMoveAndTarget : string,
    selectionDescriptionSubject : string,
    selectionDescriptionTarget : string,
    selectionDescriptionVacate: string,

    selectionPromptDrop : string,
    selectionPromptMove : string,
    selectionPromptNull : string,
    selectionPromptSubject : string,
    selectionPromptTarget : string,
    selectionPromptVacate : string,
}
