// <auto-generated />
using System;
using Djambi.Api.Db.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Djambi.Api.Db.Model.Migrations
{
    [DbContext(typeof(DjambiDbContext))]
    [Migration("20200729005329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Djambi.Api.Db.Model.EventKindSqlModel", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("EventKindId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("EventKinds");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "GameParametersChanged"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "GameCanceled"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "PlayerJoined"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "PlayerRemoved"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "GameStarted"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "TurnCommitted"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "TurnReset"
                        },
                        new
                        {
                            Id = (byte)8,
                            Name = "CellSelected"
                        },
                        new
                        {
                            Id = (byte)9,
                            Name = "PlayerStatusChanged"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.EventSqlModel", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActingPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EffectsJson")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("EventKindId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("ActingPlayerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.GameSqlModel", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowGuests")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentTurnJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("GameStatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PiecesJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("RegionCount")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("TurnCycleJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GameId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.GameStatusSqlModel", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("GameStatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("GameStatuses");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Over"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.NeutralPlayerNameSqlModel", b =>
                {
                    b.Property<int>("NeutralPlayerNameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("NeutralPlayerNameId");

                    b.ToTable("NeutralPlayerNames");

                    b.HasData(
                        new
                        {
                            NeutralPlayerNameId = 0,
                            Name = "SPORKMASTER"
                        },
                        new
                        {
                            NeutralPlayerNameId = 1,
                            Name = "dwight-schrute"
                        },
                        new
                        {
                            NeutralPlayerNameId = 2,
                            Name = "1337h4x"
                        },
                        new
                        {
                            NeutralPlayerNameId = 3,
                            Name = "DragonBjorn"
                        },
                        new
                        {
                            NeutralPlayerNameId = 4,
                            Name = "docta-octagon"
                        },
                        new
                        {
                            NeutralPlayerNameId = 5,
                            Name = "Sam_I_Am"
                        },
                        new
                        {
                            NeutralPlayerNameId = 6,
                            Name = "New_Boots"
                        },
                        new
                        {
                            NeutralPlayerNameId = 7,
                            Name = "mysterious-stranger"
                        },
                        new
                        {
                            NeutralPlayerNameId = 8,
                            Name = "Riemann"
                        },
                        new
                        {
                            NeutralPlayerNameId = 9,
                            Name = "PT3R0D4C7YL"
                        },
                        new
                        {
                            NeutralPlayerNameId = 10,
                            Name = "Rhombicuboctohedron"
                        },
                        new
                        {
                            NeutralPlayerNameId = 11,
                            Name = "Schmorpheus"
                        },
                        new
                        {
                            NeutralPlayerNameId = 12,
                            Name = "TheMangler"
                        },
                        new
                        {
                            NeutralPlayerNameId = 13,
                            Name = "ManBearPig"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.PlayerKindSqlModel", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("PlayerKindId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayerKinds");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "User"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Guest"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Neutral"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.PlayerSqlModel", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte?>("ColorId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<byte>("PlayerKindId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("PlayerStatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("StartingRegion")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("StartingTurnNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasAlternateKey("GameId", "Name");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.PlayerStatusSqlModel", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("PlayerStatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PlayerStatuses");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Alive"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Eliminated"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Conceded"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "WillConcede"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "AcceptsDraw"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "Victorious"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.PrivilegeSqlModel", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("PrivilegeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "EditUsers"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "EditPendingGames"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "OpenParticipation"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "ViewGames"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Snapshots"
                        });
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.SessionSqlModel", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.SnapshotSqlModel", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SnapshotId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GameId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.UserPrivilegeSqlModel", b =>
                {
                    b.Property<int>("UserPrivilegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("PrivilegeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserSqlModelUserId")
                        .HasColumnType("int");

                    b.HasKey("UserPrivilegeId");

                    b.HasIndex("UserSqlModelUserId");

                    b.ToTable("UserPrivileges");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.UserSqlModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("FailedLoginAttempts")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("LastFailedLoginAttemptOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.EventSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.PlayerSqlModel", "ActingPlayer")
                        .WithMany()
                        .HasForeignKey("ActingPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Djambi.Api.Db.Model.GameSqlModel", "Game")
                        .WithMany("Events")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.GameSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.PlayerSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.GameSqlModel", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.SessionSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.SnapshotSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Djambi.Api.Db.Model.GameSqlModel", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Djambi.Api.Db.Model.UserPrivilegeSqlModel", b =>
                {
                    b.HasOne("Djambi.Api.Db.Model.UserSqlModel", null)
                        .WithMany("UserPrivileges")
                        .HasForeignKey("UserSqlModelUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
