/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CellDto,
    CellDtoFromJSON,
    CellDtoFromJSONTyped,
    CellDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface BoardDto
 */
export interface BoardDto {
    /**
     * 
     * @type {number}
     * @memberof BoardDto
     */
    readonly regionCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BoardDto
     */
    readonly regionSize?: number;
    /**
     * 
     * @type {Array<CellDto>}
     * @memberof BoardDto
     */
    readonly cells: Array<CellDto>;
}

export function BoardDtoFromJSON(json: any): BoardDto {
    return BoardDtoFromJSONTyped(json, false);
}

export function BoardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionCount': !exists(json, 'regionCount') ? undefined : json['regionCount'],
        'regionSize': !exists(json, 'regionSize') ? undefined : json['regionSize'],
        'cells': ((json['cells'] as Array<any>).map(CellDtoFromJSON)),
    };
}

export function BoardDtoToJSON(value?: BoardDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


