/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreationSource
 */
export interface CreationSource {
    /**
     * 
     * @type {number}
     * @memberof CreationSource
     */
    readonly userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreationSource
     */
    readonly userName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreationSource
     */
    readonly time?: Date;
}

export function CreationSourceFromJSON(json: any): CreationSource {
    return CreationSourceFromJSONTyped(json, false);
}

export function CreationSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
    };
}

export function CreationSourceToJSON(value?: CreationSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


