/* tslint:disable */
/* eslint-disable */
/**
 * Djambi-N API
 * API for Djambi-N
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlayerKind,
    PlayerKindFromJSON,
    PlayerKindFromJSONTyped,
    PlayerKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreatePlayerRequestDto
 */
export interface CreatePlayerRequestDto {
    /**
     * 
     * @type {PlayerKind}
     * @memberof CreatePlayerRequestDto
     */
    kind: PlayerKind;
    /**
     * 
     * @type {number}
     * @memberof CreatePlayerRequestDto
     */
    userId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePlayerRequestDto
     */
    name?: string | null;
}

export function CreatePlayerRequestDtoFromJSON(json: any): CreatePlayerRequestDto {
    return CreatePlayerRequestDtoFromJSONTyped(json, false);
}

export function CreatePlayerRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlayerRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': PlayerKindFromJSON(json['kind']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function CreatePlayerRequestDtoToJSON(value?: CreatePlayerRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': PlayerKindToJSON(value.kind),
        'userId': value.userId,
        'name': value.name,
    };
}


