/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSnapshotRequestDto
 */
export interface CreateSnapshotRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSnapshotRequestDto
     */
    description: string;
}

export function CreateSnapshotRequestDtoFromJSON(json: any): CreateSnapshotRequestDto {
    return CreateSnapshotRequestDtoFromJSONTyped(json, false);
}

export function CreateSnapshotRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSnapshotRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function CreateSnapshotRequestDtoToJSON(value?: CreateSnapshotRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}


