/* tslint:disable */
/* eslint-disable */
/**
 * Djambi-N API
 * API for Djambi-N
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EffectKind {
    CurrentTurnChanged = 'CurrentTurnChanged',
    GameStatusChanged = 'GameStatusChanged',
    NeutralPlayerAdded = 'NeutralPlayerAdded',
    ParametersChanged = 'ParametersChanged',
    PieceAbandoned = 'PieceAbandoned',
    PieceDropped = 'PieceDropped',
    PieceEnlisted = 'PieceEnlisted',
    PieceKilled = 'PieceKilled',
    PieceMoved = 'PieceMoved',
    PieceVacated = 'PieceVacated',
    PlayerAdded = 'PlayerAdded',
    PlayerOutOfMoves = 'PlayerOutOfMoves',
    PlayerRemoved = 'PlayerRemoved',
    PlayerStatusChanged = 'PlayerStatusChanged',
    TurnCycleAdvanced = 'TurnCycleAdvanced',
    TurnCyclePlayerFellFromPower = 'TurnCyclePlayerFellFromPower',
    TurnCyclePlayerRemoved = 'TurnCyclePlayerRemoved',
    TurnCyclePlayerRoseToPower = 'TurnCyclePlayerRoseToPower'
}

export function EffectKindFromJSON(json: any): EffectKind {
    return EffectKindFromJSONTyped(json, false);
}

export function EffectKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectKind {
    return json as EffectKind;
}

export function EffectKindToJSON(value?: EffectKind | null): any {
    return value as any;
}

