/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EffectKind,
    EffectKindFromJSON,
    EffectKindFromJSONTyped,
    EffectKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface EffectDto
 */
export interface EffectDto {
    /**
     * 
     * @type {EffectKind}
     * @memberof EffectDto
     */
    kind: EffectKind;
}

export function EffectDtoFromJSON(json: any): EffectDto {
    return EffectDtoFromJSONTyped(json, false);
}

export function EffectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': EffectKindFromJSON(json['kind']),
    };
}

export function EffectDtoToJSON(value?: EffectDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': EffectKindToJSON(value.kind),
    };
}


