/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum EventKind {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9
}

export function EventKindFromJSON(json: any): EventKind {
    return EventKindFromJSONTyped(json, false);
}

export function EventKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventKind {
    return json as EventKind;
}

export function EventKindToJSON(value?: EventKind | null): any {
    return value as any;
}

