/* tslint:disable */
/* eslint-disable */
/**
 * Djambi-N API
 * API for Djambi-N
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListSortDirection,
    ListSortDirectionFromJSON,
    ListSortDirectionFromJSONTyped,
    ListSortDirectionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EventsQueryDto
 */
export interface EventsQueryDto {
    /**
     * 
     * @type {number}
     * @memberof EventsQueryDto
     */
    maxResults?: number | null;
    /**
     * 
     * @type {ListSortDirection}
     * @memberof EventsQueryDto
     */
    direction?: ListSortDirection;
    /**
     * 
     * @type {Date}
     * @memberof EventsQueryDto
     */
    thresholdTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof EventsQueryDto
     */
    thresholdEventId?: number | null;
}

export function EventsQueryDtoFromJSON(json: any): EventsQueryDto {
    return EventsQueryDtoFromJSONTyped(json, false);
}

export function EventsQueryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsQueryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxResults': !exists(json, 'maxResults') ? undefined : json['maxResults'],
        'direction': !exists(json, 'direction') ? undefined : ListSortDirectionFromJSON(json['direction']),
        'thresholdTime': !exists(json, 'thresholdTime') ? undefined : (json['thresholdTime'] === null ? null : new Date(json['thresholdTime'])),
        'thresholdEventId': !exists(json, 'thresholdEventId') ? undefined : json['thresholdEventId'],
    };
}

export function EventsQueryDtoToJSON(value?: EventsQueryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maxResults': value.maxResults,
        'direction': ListSortDirectionToJSON(value.direction),
        'thresholdTime': value.thresholdTime === undefined ? undefined : (value.thresholdTime === null ? null : value.thresholdTime.toISOString()),
        'thresholdEventId': value.thresholdEventId,
    };
}


