/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StringFSharpOption,
    StringFSharpOptionFromJSON,
    StringFSharpOptionFromJSONTyped,
    StringFSharpOptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface GameParameters
 */
export interface GameParameters {
    /**
     * 
     * @type {StringFSharpOption}
     * @memberof GameParameters
     */
    description?: StringFSharpOption;
    /**
     * 
     * @type {number}
     * @memberof GameParameters
     */
    readonly regionCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameParameters
     */
    readonly isPublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameParameters
     */
    readonly allowGuests?: boolean;
}

export function GameParametersFromJSON(json: any): GameParameters {
    return GameParametersFromJSONTyped(json, false);
}

export function GameParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : StringFSharpOptionFromJSON(json['description']),
        'regionCount': !exists(json, 'regionCount') ? undefined : json['regionCount'],
        'isPublic': !exists(json, 'isPublic') ? undefined : json['isPublic'],
        'allowGuests': !exists(json, 'allowGuests') ? undefined : json['allowGuests'],
    };
}

export function GameParametersToJSON(value?: GameParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': StringFSharpOptionToJSON(value.description),
    };
}


