/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum GameStatus {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

export function GameStatusFromJSON(json: any): GameStatus {
    return GameStatusFromJSONTyped(json, false);
}

export function GameStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatus {
    return json as GameStatus;
}

export function GameStatusToJSON(value?: GameStatus | null): any {
    return value as any;
}

