/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Int32FSharpOption
 */
export interface Int32FSharpOption {
    /**
     * 
     * @type {number}
     * @memberof Int32FSharpOption
     */
    readonly value?: number;
}

export function Int32FSharpOptionFromJSON(json: any): Int32FSharpOption {
    return Int32FSharpOptionFromJSONTyped(json, false);
}

export function Int32FSharpOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Int32FSharpOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function Int32FSharpOptionToJSON(value?: Int32FSharpOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


