/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationDto
 */
export interface LocationDto {
    /**
     * 
     * @type {number}
     * @memberof LocationDto
     */
    readonly region?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationDto
     */
    readonly x?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationDto
     */
    readonly y?: number;
}

export function LocationDtoFromJSON(json: any): LocationDto {
    return LocationDtoFromJSONTyped(json, false);
}

export function LocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'region': !exists(json, 'region') ? undefined : json['region'],
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
    };
}

export function LocationDtoToJSON(value?: LocationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


