/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PieceKind {
    Conduit = 'Conduit',
    Thug = 'Thug',
    Scientist = 'Scientist',
    Hunter = 'Hunter',
    Diplomat = 'Diplomat',
    Reaper = 'Reaper',
    Corpse = 'Corpse'
}

export function PieceKindFromJSON(json: any): PieceKind {
    return PieceKindFromJSONTyped(json, false);
}

export function PieceKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): PieceKind {
    return json as PieceKind;
}

export function PieceKindToJSON(value?: PieceKind | null): any {
    return value as any;
}

