/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Int32FSharpOption,
    Int32FSharpOptionFromJSON,
    Int32FSharpOptionFromJSONTyped,
    Int32FSharpOptionToJSON,
    PieceKind,
    PieceKindFromJSON,
    PieceKindFromJSONTyped,
    PieceKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface Piece
 */
export interface Piece {
    /**
     * 
     * @type {number}
     * @memberof Piece
     */
    readonly id?: number;
    /**
     * 
     * @type {PieceKind}
     * @memberof Piece
     */
    kind?: PieceKind;
    /**
     * 
     * @type {Int32FSharpOption}
     * @memberof Piece
     */
    playerId?: Int32FSharpOption;
    /**
     * 
     * @type {number}
     * @memberof Piece
     */
    readonly originalPlayerId?: number;
    /**
     * 
     * @type {number}
     * @memberof Piece
     */
    readonly cellId?: number;
}

export function PieceFromJSON(json: any): Piece {
    return PieceFromJSONTyped(json, false);
}

export function PieceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Piece {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'kind': !exists(json, 'kind') ? undefined : PieceKindFromJSON(json['kind']),
        'playerId': !exists(json, 'playerId') ? undefined : Int32FSharpOptionFromJSON(json['playerId']),
        'originalPlayerId': !exists(json, 'originalPlayerId') ? undefined : json['originalPlayerId'],
        'cellId': !exists(json, 'cellId') ? undefined : json['cellId'],
    };
}

export function PieceToJSON(value?: Piece | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': PieceKindToJSON(value.kind),
        'playerId': Int32FSharpOptionToJSON(value.playerId),
    };
}


