/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PlayerStatus {
    Pending = 'Pending',
    Alive = 'Alive',
    Eliminated = 'Eliminated',
    Conceded = 'Conceded',
    WillConcede = 'WillConcede',
    AcceptsDraw = 'AcceptsDraw',
    Victorious = 'Victorious'
}

export function PlayerStatusFromJSON(json: any): PlayerStatus {
    return PlayerStatusFromJSONTyped(json, false);
}

export function PlayerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStatus {
    return json as PlayerStatus;
}

export function PlayerStatusToJSON(value?: PlayerStatus | null): any {
    return value as any;
}

