/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PlayerStatus {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7
}

export function PlayerStatusFromJSON(json: any): PlayerStatus {
    return PlayerStatusFromJSONTyped(json, false);
}

export function PlayerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStatus {
    return json as PlayerStatus;
}

export function PlayerStatusToJSON(value?: PlayerStatus | null): any {
    return value as any;
}

