/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Privilege {
    EditUsers = 'EditUsers',
    EditPendingGames = 'EditPendingGames',
    OpenParticipation = 'OpenParticipation',
    ViewGames = 'ViewGames',
    Snapshots = 'Snapshots'
}

export function PrivilegeFromJSON(json: any): Privilege {
    return PrivilegeFromJSONTyped(json, false);
}

export function PrivilegeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Privilege {
    return json as Privilege;
}

export function PrivilegeToJSON(value?: Privilege | null): any {
    return value as any;
}

