/* tslint:disable */
/* eslint-disable */
/**
 * Djambi-N API
 * API for Djambi-N
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SelectionKind {
    Subject = 'Subject',
    Move = 'Move',
    Target = 'Target',
    Drop = 'Drop',
    Vacate = 'Vacate'
}

export function SelectionKindFromJSON(json: any): SelectionKind {
    return SelectionKindFromJSONTyped(json, false);
}

export function SelectionKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionKind {
    return json as SelectionKind;
}

export function SelectionKindToJSON(value?: SelectionKind | null): any {
    return value as any;
}

