/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SelectionKind,
    SelectionKindFromJSON,
    SelectionKindFromJSONTyped,
    SelectionKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface SelectionKindFSharpOption
 */
export interface SelectionKindFSharpOption {
    /**
     * 
     * @type {SelectionKind}
     * @memberof SelectionKindFSharpOption
     */
    value?: SelectionKind;
}

export function SelectionKindFSharpOptionFromJSON(json: any): SelectionKindFSharpOption {
    return SelectionKindFSharpOptionFromJSONTyped(json, false);
}

export function SelectionKindFSharpOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionKindFSharpOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : SelectionKindFromJSON(json['value']),
    };
}

export function SelectionKindFSharpOptionToJSON(value?: SelectionKindFSharpOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': SelectionKindToJSON(value.value),
    };
}


