/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Int32FSharpOption,
    Int32FSharpOptionFromJSON,
    Int32FSharpOptionFromJSONTyped,
    Int32FSharpOptionToJSON,
    SelectionKind,
    SelectionKindFromJSON,
    SelectionKindFromJSONTyped,
    SelectionKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface Selection
 */
export interface Selection {
    /**
     * 
     * @type {SelectionKind}
     * @memberof Selection
     */
    kind?: SelectionKind;
    /**
     * 
     * @type {number}
     * @memberof Selection
     */
    readonly cellId?: number;
    /**
     * 
     * @type {Int32FSharpOption}
     * @memberof Selection
     */
    pieceId?: Int32FSharpOption;
}

export function SelectionFromJSON(json: any): Selection {
    return SelectionFromJSONTyped(json, false);
}

export function SelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Selection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': !exists(json, 'kind') ? undefined : SelectionKindFromJSON(json['kind']),
        'cellId': !exists(json, 'cellId') ? undefined : json['cellId'],
        'pieceId': !exists(json, 'pieceId') ? undefined : Int32FSharpOptionFromJSON(json['pieceId']),
    };
}

export function SelectionToJSON(value?: Selection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': SelectionKindToJSON(value.kind),
        'pieceId': Int32FSharpOptionToJSON(value.pieceId),
    };
}


