/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringFSharpOption
 */
export interface StringFSharpOption {
    /**
     * 
     * @type {string}
     * @memberof StringFSharpOption
     */
    readonly value?: string | null;
}

export function StringFSharpOptionFromJSON(json: any): StringFSharpOption {
    return StringFSharpOptionFromJSONTyped(json, false);
}

export function StringFSharpOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringFSharpOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StringFSharpOptionToJSON(value?: StringFSharpOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


