/* tslint:disable */
/* eslint-disable */
/**
 * Djambi-N API
 * API for Djambi-N
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TurnStatus {
    AwaitingSelection = 'AwaitingSelection',
    AwaitingCommit = 'AwaitingCommit',
    DeadEnd = 'DeadEnd'
}

export function TurnStatusFromJSON(json: any): TurnStatus {
    return TurnStatusFromJSONTyped(json, false);
}

export function TurnStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TurnStatus {
    return json as TurnStatus;
}

export function TurnStatusToJSON(value?: TurnStatus | null): any {
    return value as any;
}

