/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Turn,
    TurnFromJSON,
    TurnFromJSONTyped,
    TurnToJSON,
} from './';

/**
 * 
 * @export
 * @interface TurnFSharpOption
 */
export interface TurnFSharpOption {
    /**
     * 
     * @type {Turn}
     * @memberof TurnFSharpOption
     */
    value?: Turn;
}

export function TurnFSharpOptionFromJSON(json: any): TurnFSharpOption {
    return TurnFSharpOptionFromJSONTyped(json, false);
}

export function TurnFSharpOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TurnFSharpOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : TurnFromJSON(json['value']),
    };
}

export function TurnFSharpOptionToJSON(value?: TurnFSharpOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': TurnToJSON(value.value),
    };
}


