/* tslint:disable */
/* eslint-disable */
/**
 * Apex API
 * API for Apex
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TurnStatus {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

export function TurnStatusFromJSON(json: any): TurnStatus {
    return TurnStatusFromJSONTyped(json, false);
}

export function TurnStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TurnStatus {
    return json as TurnStatus;
}

export function TurnStatusToJSON(value?: TurnStatus | null): any {
    return value as any;
}

